title: Apollo
url: https://apollo.vikash.me     # add your site URL if needed
baseurl: ''                       # adjust if your site is in a subfolder

# Include directories that you want Jekyll to process
include: ['_pages']

# Exclude files or directories not meant for the final build
exclude: ['_includes/notes_graph.json', 'node_modules', 'vendor']

# Use .html extension? (set false if you prefer pretty URLs without .html)
use_html_extension: false

# Open external links in new tab for privacy/safety
open_external_links_in_new_tab: true

# Replace tweet URLs with embeds? (beware of privacy tradeoffs)
embed_tweets: false

permalink: pretty

plugins:
  - jekyll-last-modified-at
  - jekyll-seo-tag     # added for better SEO
  - jekyll-feed        # added for RSS

sass:
  sass_dir: _sass
  style: :compressed

collections:
  notes:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/*"
    values:
      layout: default
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: note