name: Build and Deploy Jekyll Site to App Engine

on:
  push:
    branches: [ main ]
  # (Optional) you can also trigger this via repository_dispatch or schedule

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code (include submodules if you use them)
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true

      # 2. Set up Ruby environment
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # adjust to your preferred Ruby version

      # 3. Install Gem dependencies and build the site
      - name: Install Gems and Build Site
        run: |
          bundle install
          bundle exec jekyll build

      # 4. Set up Google Cloud SDK
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: your-gcp-project-id   # Replace with your actual project ID

      # 5. Deploy to App Engine
      - name: Deploy to App Engine
        run: |
          gcloud app deploy --quiet